### ISSUE TITLE
Life/Dead status in different columns

### ISSUE THREAD

**Issue by ValentineHerr** [Alliance-for-Tropical-Forest-Science/DataHarmonization#1]
Currently I only ask for one `LifeStatus` column, and the user needs to select the values in `LifeStatus` that mean "dead" and the one that mean "alive". Any other value is considered as "NA".

This works well except that ForestPlots (which is following RAINFOR) has 2 different columns:
One for "alive status" (`F1`, and trees that are dead get a "0" there) and one for "dead status" (`F2`, and trees that are alive get a "1" there). 

See https://rainfor.org/wp-content/uploads/sites/129/2022/06/RAINFOR_data_codes_EN.pdf

If we only ask for one column, we can capture one status properly (e.g. if `F2` is selected, we can accurately say who is "alive"  but we won't have an exhaustive list of the all the possible codes for dead trees... thus, some dead status may be changed to "NA" in a different dataset).

I can "easily" fix that by asking 2 times for a status column. One that gives a clear picture of who is "alive" and one for the "dead" ones. Most plots may select the same column for both, but ForestPlots, will be able to select `F2` and `F1`, respectively. So they will be able to select "1" in `F2` to indicate the trees that are "alive" and "0" in `F1` to indicate the trees that "dead".

@cpiponiot do you know other networks that may benefit from that?

The problem with this, is that it will make the profiles that already exist obsolete.... so people will need to update their profile.
But I think it is worth it...

**Comment by ValentineHerr** [comment]
I am making the change.

I have some popup window that will let the use know their profile is obsolete:
 - if used as input profile:

![image](https://user-images.githubusercontent.com/19673377/236057379-5c2885c0-1c2a-4b45-8244-0471ed8aabe8.png)

 - if used as output profile:
![image](https://user-images.githubusercontent.com/19673377/235936316-29c23d08-f51f-4d09-8b72-bc3bffac9d83.png)

**Comment by cpiponiot** [comment]
In all the plots and networks I can think of, there was a single column for dead/live status, and the codes were specified in one or two different columns. But even if only for ForestPlots formatted data, it's already very useful to be able to integrate the data this way, and the "expired profile" is a great way of dealing with this!
