### ISSUE TITLE
anticipate new column names when tidying

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#10]
When tidying the data, there are new column names, for example CensusID. These column names are not easily identified by the user later. It would be good to add a warning for the user, "remember that there will be a new column name called CensusID" or something like that.

Besides, what happens if there is already a column "CensusID"? It might happen in some cases.

**Comment by ValentineHerr** [comment]
I added some text about the new column names:

![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/f6890d31-bfb4-4007-b4ea-0192d6a778d8)

Not sure what would happen if e.g.  there is already a column "CensusID" in the data. Banking on the unlikeliness of this for now....
