### ISSUE TITLE
Not obvious explanation in the "tidying" step

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#12]
Some users list long lists of things that are repeated, instead of grouping the pairs or triplets of variable names that apply. 

For example, in a database that has these variables:

dbh
dbh_time2
height
height_time2
is_alive
is_alive_time2

they list "dbh, height, is_alive" once, instead of listing

dbh, dbh_time2
height, height_time2
is_alive, is_alive2

I guess the text that guides the user in creating these clusters of variables is not very transparent. Perhaps some examples are helpful.

**Comment by gabrielareto** [comment]
It may be better to reverse the order in which the user provides info:

1) list variables that belong to the same group or measure the same thing at different times or censuses or the same thing using different methods. For example, "dbh_in_cm_first_census" and "dbh_in_cm_second_census". 

2) under which name do you want to group these variables? For example, "dbh_in_cm".

**Comment by gabrielareto** [comment]
Users may or may not what "tidy" means. A user suggests adding a gif or a figure explaining what will happen in this process.

**Comment by ValentineHerr** [comment]
> they list "dbh, height, is_alive" once, instead of listing
> 
> dbh, dbh_time2 height, height_time2 is_alive, is_alive2

In this case I think those users nmay have been right to not include _dbh_time2_ as it may already exist in _dbh_ of the previous census. But if that is the case, there should not be a need for tidying. (Of more clearer example would be for a dataset with _previousDBH_ and _DBH_. the _previousDBH_ column can be ignored.

**Comment by ValentineHerr** [comment]
> It may be better to reverse the order in which the user provides info:
> 
> 1. list variables that belong to the same group or measure the same thing at different times or censuses or the same thing using different methods. For example, "dbh_in_cm_first_census" and "dbh_in_cm_second_census".
> 2. under which name do you want to group these variables? For example, "dbh_in_cm".

these are good ideas that I'll work on

**Comment by ValentineHerr** [comment]
now the tidying part looks like this:

![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/8bbccbd6-01c2-40e2-8d28-4469e5a9bf21)

**Comment by ValentineHerr** [comment]
> A user suggests adding a gif or a figure explaining what will happen in this process.

There is GIF in the help file, that shows what happen. But I'll try to make a schematic when I have a moment, to add on the tidy tab.

**Comment by ValentineHerr** [comment]
How is this looking?

![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/c218d407-9311-4b01-be4b-04dc92606897)

**Comment by gabrielareto** [comment]
This looks good. But I think it would be better if things are in a long list, not in two columns, and the list of radio buttons appears complete: 

![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/8447831/924b1168-c8fd-4a02-8eb0-95f034431207)

**Comment by ValentineHerr** [comment]
> I think it is easier to keep track of progress if we use just one column.

It is already in one column, it was for the example that I put it in two columns. to save space. I changed that in the new version here:

![TidyExample](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/772e22fa-aedc-49e6-bcd9-d5e1bcef497b)

**Comment by gabrielareto** [comment]
ooooook. I see. This looks great.
