### ISSUE TITLE
decimals separated by commas

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#13]
A dataset is giving problems, always appearing with decimals separated by commas.

We have saved it as csv, UTF-8, and when opening it in Excel or as a text file the decimal degrees seem separated by dots, not commas. Still, decimals appear with commas in Shiny, making most DBHs to end as NA in the output table.

I cannot see how this could be an app problem. It seems an Excel problem, but I report just in case.

**Comment by ValentineHerr** [comment]
if you want to send me the dataset I can try to troubleshoot

**Comment by gabrielareto** [comment]
I don't have access to the dataset and the user did not follow up. I close for the moment.
