### ISSUE TITLE
users with too many columns as input

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#14]
Some users have many columns and get overwhelmed by the dropdown menus. They suggest an intermediate step, somewhere before declaring headers, to filter their tables, so they check the columns of interest only.

**Comment by ValentineHerr** [comment]
I added a place to "focus" on a set of columns. The selection is saved in the profile so it gets updated when the profile is uploaded. It does not delete the columns, but it organizes them in the dropdown menus (top of the dropdown is the "focused" columns, bottom are the "others")

![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/1ca6cf8a-e50b-4bcd-8168-a1b37758e20f)
