### ISSUE TITLE
upload everything at the beggining

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#17]
It seems more intuitive to upload everything at the start, in the first tab:

(1) number of tables --> upload your tables
(2) upload the profile of your input, if you have it
(3) upload / pick the profile that describes your desired output, if you have it

this first tab is the place to explain the general process:

your data + description of your data format + description of your desired output format = your data in the desired output format

**Comment by ValentineHerr** [comment]
Bringing in [@gabrielareto's comment](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/issues/46#issuecomment-1674975067) here:

related to this idea of pairs of {data in format X, description of format X}:

it can be more clear for the user, to understand how the app works, if they declare the input profile and the output profile at the same time, not in different tabs. Something like:

1- load your data
2- profiles etc.

do you have a description of your input? Pick from the list, or provide a rds object that blah blah blah.

if in the list, pick it.
if not on the list: load it. It can be an incomplete profile, you can update it later.
if you do not have it: you will create it in tab "headers and units".
do you have a description of your desired output? Pick from the list, or provide a rds object that blah blah blah. This is typically a consensus format in collaborations, and may be provided to you by the person(s) responsible for data aggregation. It could also be the format of a network or repository in which you want to integrate your data.

if in the list, pick it.
if not on the list: load it.
if you do not have it: the app will return data in a default standard format.
3- headers and units. In case you want to create/update the description of the input data.

etc.

are there reasons why this could be more difficult for us or the users than the current design?

**Comment by ValentineHerr** [comment]
Now uploading everything at the beginning.
![issue41DataHarmo](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/add52d70-c5a4-466b-b2b8-9ee0d26ef58b)
