### ISSUE TITLE
names of the blocks in "headers and units"

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#20]
The names of the blocks in "headers and units" are not too clear.

- "plot measurements" for what seem to be mostly data summaries at the plot level. Perhaps "summaries at the plot level" or "plot attributes"
- tree/stem information --> if these are just tree identifiers, just call the block "tree/stem identifiers"
- the same with identifiers for plots/sites/subplots

May add more later

**Comment by ValentineHerr** [comment]
I improved the naming for bullet 1 and 2 but for this third one

> * the same with identifiers for plots/sites/subplots

I think I am going to leave it as is, since there are things like plot area, soil type, treatment etc... I feel that those are not really identifiers.... Do you agree?
