### ISSUE TITLE
do not remove trees below minimum dbh

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#23]
Are trees below minimum dbh removed in any step? Don't do it. Trees could be 10.00 cm at census 1 and 9.99 cm at census 2, etc. It is ok to follow these trees regardless of how their dbh changes.

**Comment by ValentineHerr** [comment]
> Are trees below minimum dbh removed in any step?

they are not (unless diameter corrections are used, I believe that function removes trees <MinDBH)
