### ISSUE TITLE
StatusCorrectionPlot - example don't pass

### ISSUE THREAD

**Issue by VincyaneBadouard** [Alliance-for-Tropical-Forest-Science/DataHarmonization#3]
https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/blob/fd76a4d0a6ad7f79b88066555cf2689431a689a8/R/StatusCorrectionPlot.R#L32

"Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto), :
Le zone active (Viewport) a des dimensions nulles"

**Comment by ValentineHerr** [comment]
@VincyaneBadouard This is because of the size of the RStidy Plot panel. Runing the example on a big monitor does not give the error.
I'll change `severalWindows`  to `TRUE` and that will avoid the issue.
