### ISSUE TITLE
profiles kept with date or easy-to-read timestamps

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#30]
users keep several profiles during the process, some of them mentioned that it could be useful to add versions to them (I assume date and human-readable time is the most robust way to go)

**Comment by ValentineHerr** [comment]
To me there is really no reason to keep several versions of a profile. Profile that are saved during the process of a same dataset should be overwritten (equivalent of hitting a "save" button in a Word document). Profiles that belong to different datasets should be named by the user's own naming convention. If they want to add a date to it, they can.

**Comment by gabrielareto** [comment]
yes, I agree. Also, adding version names is an invitation to keep multiple versions even for users who did not plan to do so. It does not seem a good idea. 

I do not remember why I thought this issue made sense. I will try to understand the reasoning of the users if this issue comes up again. There should be reasons beyond "I will do it just in case" for us to act on it.
