### ISSUE TITLE
mixing individual-level and stem-level table

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#35]
Some users want to merge datasets from stem-level tables and tree-level tables. Is the app useful for that?

For teams that measure 1 stem per tree: Is it OK to declare "stem-level" as the more detailed level of the table? I do not see how individual-level vs. stem-level can make a difference.

**Comment by ValentineHerr** [comment]
> For teams that measure 1 stem per tree: Is it OK to declare "stem-level" as the more detailed level of the table?
yes, that won't cause the app to fail (and there is no difference on how the data is treated).



> Some users want to merge datasets from stem-level tables and tree-level tables. Is the app useful for that?

You mean they may have a tree table with individual level information and want to merge in stem level info (that is possible) or do you mean they may have a table with data for the main stem and then another table for stemtag>1 ? (in that case the tables would need to be stacked and not merged).

**Comment by gabrielareto** [comment]
all clear.
