### ISSUE TITLE
table pre view in "headers and units" step

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#41]
Users look at their tables constantly when working on this tab. The previous tab had a preview. But it seems useful to have a preview in the "headers and units" tab itself. 

For example, in a single column, one thing below the other:
(1) pre visualization of the plot headers and content
(2) step 1 (stuff that is on the table)
(3) step 2 (stuff that needs to be declared independently)

**Comment by ValentineHerr** [comment]
headers tab looks like this now:

![issue41DataHarmo](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/99a649e3-e900-41c4-bf78-b65d0bb45a0b)

**Comment by gabrielareto** [comment]
great, thanks!
