### ISSUE TITLE
error with "pass.this.unique" within tnrs?

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#50]
![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/8447831/68cb653b-f423-4bf5-b9ca-4a91b3252c28)

**Comment by ValentineHerr** [comment]
this should not be an issue now that we are using WFO instead of "tropicos" in the botanical correction function.
