### ISSUE TITLE
Letters with ¨

### ISSUE THREAD

**Issue by gabrielareto** [Alliance-for-Tropical-Forest-Science/DataHarmonization#6]
Letters with ¨ appear as "?" within a black romboid in the pre-visualization in the app. I do not know if this is a problem that is carried to the output, or just a problem in that visualization in the shiny app. It affects to author names, mostly.

**Comment by ValentineHerr** [comment]
I tried to reproduce the issue but the special character is read properly for me.

![image](https://github.com/Alliance-for-Tropical-Forest-Science/DataHarmonization/assets/19673377/5f69a32f-9f9d-40b4-96f7-8b1982e73219)

There is not much I can do about this. Dealing with special characters and the encoding of the original file is very difficult.
